services:
  portfolio-app:
    image: ${IMAGE}
    container_name: portfolio-app
    restart: always
    ports:
      - "3200:80"
    volumes:
      - ${DEPLOY_PATH}/cv.pdf:/usr/share/nginx/html/cv.pdf:ro
    networks:
      - web

networks:
  web:
    external: true
    name: web
