services:
  portfolio-app:
    image: ${IMAGE}
    container_name: portfolio-app
    restart: always
    ports:
      - "3200:80"
    networks:
      - web

networks:
  web:
    external: true
    name: web
